on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: macOS-15
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Checkout Wine
      uses: actions/checkout@v4
      with:
        repository: "wine-mirror/wine"
        ref: "wine-10.6"
        path: wine
    - name: Checkout libinotify-kqueue
      uses: actions/checkout@v4
      with:
        repository: "libinotify-kqueue/libinotify-kqueue"
        ref: "20240724"
        path: libinotify-kqueue
    - name: Install Dependencies
      run: brew install bison mingw-w64 autoconf automake
    - name: Install libinotify-kqueue
      working-directory: libinotify-kqueue
      run: |
        autoreconf -fvi
        ./configure --prefix=/usr/local --build=x86_64-apple-darwin
        make -j$(sysctl -n hw.logicalcpu)
        make install
    - name: Configure wine
      working-directory: wine
      # https://github.com/Gcenx/macOS_Wine_builds?tab=readme-ov-file#configure-options
      run: |
        export PATH="$(brew --prefix bison)/bin:$PATH"
        ./configure --build=x86_64-apple-darwin \
        --enable-archs=i386,x86_64 \
        --disable-tests \
        --disable-winebth_sys \
        --without-alsa \
        --without-capi \
        --with-coreaudio \
        --with-cups \
        --without-dbus \
        --with-ffmpeg \
        --with-freetype \
        --with-gettext \
        --without-gettextpo \
        --without-gphoto \
        --with-gnutls \
        --without-gssapi \
        --with-gstreamer \
        --with-inotify \
        --without-krb5 \
        --with-mingw \
        --without-netapi \
        --with-opencl \
        --with-opengl \
        --without-oss \
        --with-pcap \
        --with-pcsclite \
        --with-pthread \
        --without-pulse \
        --without-sane \
        --with-sdl \
        --without-udev \
        --with-unwind \
        --without-usb \
        --without-v4l2 \
        --with-vulkan \
        --without-wayland \
        --without-x11 \
